-- ANTES: O PLANO DE EXECUCAO DESCREVIA UM CUSTO DE 84859, num tempo de 807ms!
SELECT
	COUNT(H.ID_HISTORICO) AS ESTAO_ABERTAS
FROM
	HELP_HISTORICOS H
JOIN
	HELP_SOLICITACOES S ON S.ID_SOLICITACAO = H.FK_SOLICITACAO
WHERE
	H.ID_HISTORICO = (
		SELECT
			ID_HISTORICO
		FROM
			(SELECT
				H2.ID_HISTORICO,
				H2.FK_SOLICITACAO
			FROM
				HELP_HISTORICOS H2
			ORDER BY
				H2.DATA_INSERCAO DESC
			) TAB
		WHERE
			TAB.FK_SOLICITACAO = H.FK_SOLICITACAO
		AND
			ROWNUM = 1
	)
AND
	H.FK_STATUS = 1

-- DEPOIS: O CUSTO PASSOU PARA APENAS 245, num tempo de 13ms!
SELECT
	COUNT(H.ID_HISTORICO) AS ESTAO_ABERTAS
FROM
	HELP_HISTORICOS H
JOIN (
		SELECT
			FK_SOLICITACAO,
			MAX(ID_HISTORICO) AS MOVIMENTACAO_MAIS_RECENTE
		FROM
			HELP_HISTORICOS
		GROUP BY
			FK_SOLICITACAO
		ORDER BY
			FK_SOLICITACAO ASC
	) MMR ON
	H.ID_HISTORICO = MMR.MOVIMENTACAO_MAIS_RECENTE
WHERE
	H.FK_STATUS = 1
	
	