--COMO ERA
SELECT
	ID_HISTORICO
FROM
	HELP_HISTORICOS H
JOIN
	HELP_SOLICITACOES S ON S.ID_SOLICITACAO = H.FK_SOLICITACAO
WHERE
	H.ID_HISTORICO = (
		SELECT
			ID_HISTORICO
		FROM
			(SELECT
				H2.ID_HISTORICO,
				H2.FK_SOLICITACAO
			FROM
				HELP_HISTORICOS H2
			ORDER BY
				H2.DATA_INSERCAO DESC
			) TAB
		WHERE
			TAB.FK_SOLICITACAO = H.FK_SOLICITACAO
		AND
			ROWNUM = 1
	)
--AND
--	H.FK_STATUS = 1


-- COMO FICOU
SELECT
--	H.FK_SOLICITACAO,
--	H.FK_STATUS AS ESTAO_ABERTAS
H.ID_HISTORICO
FROM
	HELP_HISTORICOS H
JOIN (
		SELECT
			H2.FK_SOLICITACAO,
			MAX(H2.ID_HISTORICO) AS ABACATE
		FROM
			HELP_HISTORICOS H2
		GROUP BY
			H2.FK_SOLICITACAO
		ORDER BY
			H2.FK_SOLICITACAO ASC
	) S ON
	H.ID_HISTORICO = S.ABACATE
--WHERE
--	H.FK_STATUS = 1