-- FORAM REALIZADOS 3 LEFT JOIN COM A MESMA TABELA RH_FUNCIONARIOS, PARA CAPTURAR OS NOMES DOS FUNCIONÁRIOS, SERVINDO COMO UM LOOKUP

SELECT
	H.ID_HISTORICO,
	TO_CHAR(H.DATA_INSERCAO, 'DD/MM/YYYY HH24:MI:SS') AS MOVIMENTACAO,
	INITCAP(ST.DESCRICAO) AS SITUACAO,
	INITCAP(FS.NOME_FUNCIONARIO) AS SOLICITANTE, --NOTE O ALIAS 'FS'
	INITCAP(FE.NOME_FUNCIONARIO) AS ENCAMINHADA, --NOTE O ALIAS 'FE'
	INITCAP(FR.NOME_FUNCIONARIO) AS RESPONSAVEL, --NOTE O ALIAS 'FR'
	H.FK_ENCAMINHADA_POR,
	H.FK_RESPONSAVEL,
	INITCAP(P.NOME) AS PARCEIRO,
	H.OS_PARCEIRO,
	H.MENSAGEM
FROM
	HELP_HISTORICOS H
	JOIN HELP_STATUS ST ON ST.ID_STATUS = H.FK_STATUS
	LEFT JOIN RH_FUNCIONARIOS FS ON FS.COD_FUNCIONARIO = H.FK_SOLICITANTE
	LEFT JOIN RH_FUNCIONARIOS FE ON FE.COD_FUNCIONARIO = H.FK_ENCAMINHADA_POR
	LEFT JOIN RH_FUNCIONARIOS FR ON FR.COD_FUNCIONARIO = H.FK_RESPONSAVEL
	LEFT JOIN HELP_PARCEIROS P ON P.ID_PARCEIRO = H.FK_PARCEIRO
WHERE
	H.FK_SOLICITACAO = 16
ORDER BY
	H.ID_HISTORICO DESC