SELECT 
	A.DATA_VALIDADE,
	A.DATA_INSERCAO,
	A.AUTORIZADO_TRAB_ALT_ESP_CONF,
	CASE --IF else
		WHEN AUTORIZADO_TRAB_ALT_ESP_CONF = 'S' THEN --RETURN 'Sim'
			(SELECT DESCRICAO FROM MED_STATUS WHERE ID_STATUS = 1)
		ELSE 
			(SELECT DESCRICAO FROM MED_STATUS WHERE ID_STATUS = 0)
			--RETURN 'Não'
	END AS ATAEP,
	CASE A.AUTORIZADO_TRAB_ALT_ESP_CONF --switch case
		WHEN 'S' THEN 'Sim'
		WHEN 'N' THEN 'Não'
		ELSE 'Desconhecido'
	END AS TESTE_MAROTO
FROM MED_ASO A


-- outro exemplo, agora usando 2 valores (COD_TIPO_CARGO, FK_CONTRATO)
SELECT
	VFJL.MATRICULA_FUNCIONAL AS MATRICULA_FUNCIONAL,
	VFJL.NOME_FUNCIONARIO AS NOME_FUNCIONARIO,
	REPLACE(TO_CHAR(HR_ENTRADA, 'HH24:MI'), ':', 'h') AS HR_ENTRADA,
	REPLACE(TO_CHAR(HR_SAIDA, 'HH24:MI'), ':', 'h') AS HR_SAIDA,
	REPLACE(TO_CHAR(HR_ALMOCO, 'HH24:MI'), ':', 'h') AS HR_ALMOCO,
	VFJL.CARGO AS CARGO,
	CASE 
		WHEN VFJL.COD_TIPO_CARGO = 1 THEN 'COMISSIONADO'
		WHEN FCE.FK_CONTRATO = 1 THEN 'COMISSIONADO'
		WHEN FCE.FK_CONTRATO = 5 THEN 'SUBSTITUIÇÃO'
		ELSE ''
	END AS OBSERVACAO
FROM
	VW_FUNCIONARIOS_JOR_LOT VFJL
LEFT JOIN
	RH_FUNCIONARIOS_CARGOS_EXERC FCE ON FCE.FK_FUNCIONARIO = VFJL.COD_FUNCIONARIO
WHERE
	VFJL.COD_LOCAL_REPARTICAO = " . {COD_LOCAL_REPARTICAO} . "
AND
	VFJL.ATIVO = 1
ORDER BY
	VFJL.NOME_FUNCIONARIO